In [1]:
import pandas as pd

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
df=pd.read_csv('https://github.com/philoma/Dataset/raw/main/Customer%20Purchase.csv')

In [4]:
df.head()

   Customer ID  Age  Gender Education   Review Purchased
0         1021   30  Female    School  Average        No
1         1022   68  Female        UG     Poor        No
2         1023   70  Female        PG     Good        No
3         1024   72  Female        PG     Good        No
4         1025   16  Female        UG  Average        No

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Customer ID  50 non-null     int64
 1   Age          50 non-null     int64
 2   Gender       50 non-null     object
 3   Education    50 non-null     object
 4   Review       50 non-null     object
 5   Purchased    50 non-null     object
dtypes: int64(2), object(4)
memory usage: 2.5+ KB

In [6]:
df.isnull().sum()

Customer ID    0
Age            0
Gender         0
Education      0
Review         0
Purchased      0
dtype: int64

In [7]:
df=df.drop('Customer ID', axis=1)

In [8]:
df.sample(5)

    Age  Gender Education   Review Purchased
5    31  Female    School  Average       Yes
30   73    Male        UG  Average        No
4    16  Female        UG  Average        No
9    74    Male        UG     Good       Yes
15   75    Male        UG     Poor        No

In [9]:
y=df.iloc[:,-1]

In [10]:
X=df.drop('Purchased', axis=1)

Here Gender is a niminal type(so apply OHE) of data and rest X features are ordinal(so, apply Ordinal Encoder)
And on dependent(o/p) col, apply LabelEncoder

OHE using Pandas

In [11]:
pd.get_dummies(X, columns=['Gender'], drop_first=True) # dropped first col of dummy variables to tackle problem of multi collinearity and avoid dummy variable trap

    Age Education   Review  Gender_Male
0    30    School  Average            0
1    68        UG     Poor            0
2    70        PG     Good            0
3    72        PG     Good            0
4    16        UG  Average            0
5    31    School  Average            0
6    18    School     Good            1
7    60    School     Poor            0
8    65        UG  Average            0
9    74        UG     Good            1
10   98        UG     Good            0
11   74        UG     Good            1
12   51    School     Poor            1
13   57    School  Average            0
14   15        PG     Poor            1
15   75        UG     Poor            1
16   59        UG     Poor            1
17   22        UG     Poor            0
18   19    School     Good            1
19   97        PG     Poor            1
20   57    School  Average            0
21   32        PG  Average            1
22   18        PG     Poor            0
23   96    School     Good            0
24   16        PG  Average            0
25   57    School     Good            0
26   53        PG     Poor            0
27   69        PG     Poor            0
28   48    School     Poor            1
29   83        UG  Average            0
30   73        UG  Average            1
31   22    School     Poor            0
32   92        UG  Average            1
33   89        PG     Good            0
34   86    School  Average            1
35   74    School     Poor            1
36   34        UG     Good            0
37   94        PG  Average            1
38   45    School     Good            0
39   76        PG     Poor            1
40   39    School     Good            1
41   23        PG     Good            1
42   30        PG     Good            0
43   27        PG     Poor            1
44   77        UG  Average            0
45   61        PG     Poor            1
46   64        PG     Poor            0
47   38        PG     Good            0
48   39        UG     Good            0
49   25        UG     Good            0

In [12]:
# the pandas get_dummy() method is not used in projects to be deployed to prod since, it doesn't remember order of cols and reshuffles them

In [13]:
X1=df.iloc[:,0]
X2=df['Gender']
X3=df[['Education', 'Review']]

OHE using sklearn

In [14]:
from sklearn.preprocessing import OneHotEncoder

In [15]:
ohe=OneHotEncoder(drop='first')

In [20]:
df.columns

Index(['Age', 'Gender', 'Education', 'Review', 'Purchased'], dtype='object')

In [30]:
ohe.fit_transform([X2]).toarray()

array([], shape=(1, 0), dtype=float64)

In [31]:
X2.head()

0    Female
1    Female
2    Female
3    Female
4    Female
Name: Gender, dtype: object

In [32]:
ohe.categories_

[array(['Female'], dtype=object),
 array(['Female'], dtype=object),
 array(['Female'], dtype=object),
 array(['Female'], dtype=object),
 array(['Female'], dtype=object),
 array(['Female'], dtype=object),
 array(['Male'], dtype=object),
 array(['Female'], dtype=object),
 array(['Female'], dtype=object),
 array(['Male'], dtype=object),
 array(['Female'], dtype=object),
 array(['Male'], dtype=object),
 array(['Male'], dtype=object),
 array(['Female'], dtype=object),
 array(['Male'], dtype=object),
 array(['Male'], dtype=object),
 array(['Male'], dtype=object),
 array(['Female'], dtype=object),
 array(['Male'], dtype=object),
 array(['Male'], dtype=object),
 array(['Female'], dtype=object),
 array(['Male'], dtype=object),
 array(['Female'], dtype=object),
 array(['Female'], dtype=object),
 array(['Female'], dtype=object),
 array(['Female'], dtype=object),
 array(['Female'], dtype=object),
 array(['Female'], dtype=object),
 array(['Male'], dtype=object),
 array(['Female'], dtype=object),
 array(['Male'], dtype=object),
 array(['Female'], dtype=object),
 array(['Male'], dtype=object),
 array(['Female'], dtype=object),
 array(['Male'], dtype=object),
 array(['Male'], dtype=object),
 array(['Female'], dtype=object),
 array(['Male'], dtype=object),
 array(['Female'], dtype=object),
 array(['Male'], dtype=object),
 array(['Male'], dtype=object),
 array(['Male'], dtype=object),
 array(['Female'], dtype=object),
 array(['Male'], dtype=object),
 array(['Female'], dtype=object),
 array(['Male'], dtype=object),
 array(['Female'], dtype=object),
 array(['Female'], dtype=object),
 array(['Female'], dtype=object),
 array(['Female'], dtype=object)]

In [33]:
X2=pd.DataFrame(ohe.fit_transform(X[['Gender']]).toarray(), columns=['Gender_Male'])

In [35]:
X2.sample(5)

    Gender_Male
39          1.0
38          0.0
26          0.0
48          0.0
22          0.0

In [38]:
X3.sample(5)

   Education   Review
9         UG     Good
44        UG  Average
45        PG     Poor
16        UG     Poor
27        PG     Poor

Ordinal Encoder on Ordinal vectors

In [43]:
X3.nunique()

Education    3
Review       3
dtype: int64

In [45]:
X3['Education'].unique()

array(['School', 'UG', 'PG'], dtype=object)

In [46]:
X3['Review'].unique()

array(['Average', 'Poor', 'Good'], dtype=object)

In [39]:
from sklearn.preprocessing import OrdinalEncoder

In [47]:
oe=OrdinalEncoder(categories=[['School', 'UG', 'PG'],['Poor', 'Average', 'Good']])

In [49]:
X3=oe.fit_transform(X3)

In [51]:
X3=pd.DataFrame(X3, columns=['Education', 'Review'])

In [55]:
X3['Education'].dtype

dtype('float64')

In [56]:
X=pd.concat([X1, X2, X3], axis=1)

In [57]:
X

    Age  Gender_Male  Education  Review
0    30          0.0        0.0     1.0
1    68          0.0        1.0     0.0
2    70          0.0        2.0     2.0
3    72          0.0        2.0     2.0
4    16          0.0        1.0     1.0
5    31          0.0        0.0     1.0
6    18          1.0        0.0     2.0
7    60          0.0        0.0     0.0
8    65          0.0        1.0     1.0
9    74          1.0        1.0     2.0
10   98          0.0        1.0     2.0
11   74          1.0        1.0     2.0
12   51          1.0        0.0     0.0
13   57          0.0        0.0     1.0
14   15          1.0        2.0     0.0
15   75          1.0        1.0     0.0
16   59          1.0        1.0     0.0
17   22          0.0        1.0     0.0
18   19          1.0        0.0     2.0
19   97          1.0        2.0     0.0
20   57          0.0        0.0     1.0
21   32          1.0        2.0     1.0
22   18          0.0        2.0     0.0
23   96          0.0        0.0     2.0
24   16          0.0        2.0     1.0
25   57          0.0        0.0     2.0
26   53          0.0        2.0     0.0
27   69          0.0        2.0     0.0
28   48          1.0        0.0     0.0
29   83          0.0        1.0     1.0
30   73          1.0        1.0     1.0
31   22          0.0        0.0     0.0
32   92          1.0        1.0     1.0
33   89          0.0        2.0     2.0
34   86          1.0        0.0     1.0
35   74          1.0        0.0     0.0
36   34          0.0        1.0     2.0
37   94          1.0        2.0     1.0
38   45          0.0        0.0     2.0
39   76          1.0        2.0     0.0
40   39          1.0        0.0     2.0
41   23          1.0        2.0     2.0
42   30          0.0        2.0     2.0
43   27          1.0        2.0     0.0
44   77          0.0        1.0     1.0
45   61          1.0        2.0     0.0
46   64          0.0        2.0     0.0
47   38          0.0        2.0     2.0
48   39          0.0        1.0     2.0
49   25          0.0        1.0     2.0

LabelEncoder on the dependent vector

In [58]:
from sklearn.preprocessing import LabelEncoder

In [59]:
le=LabelEncoder()

In [61]:
le.fit_transform(y)

array([0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 0])

In [63]:
y=pd.DataFrame(le.fit_transform(y), columns=['Purchased'])

In [64]:
y.sample(5)

    Purchased
1           0
0           0
28          0
14          1
22          1

In [65]:
from sklearn.model_selection import train_test_split

In [68]:
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.2)

Keep Coding:)