In [ ]:
import pandas as pd
import sklearn as sns

In [ ]:
df=pd.read_csv('https://github.com/campusx-official/100-days-of-machine-learning/raw/main/day26-ordinal-encoding/customer.csv')

In [ ]:
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [ ]:
df=df.iloc[:,2:]

In [ ]:
df

     review education purchased
0   Average    School        No
1      Poor        UG        No
2      Good        PG        No
3      Good        PG        No
4   Average        UG        No
5   Average    School       Yes
6      Good    School        No
7      Poor    School       Yes
8   Average        UG        No
9      Good        UG       Yes
10     Good        UG       Yes
11     Good        UG       Yes
12     Poor    School        No
13  Average    School        No
14     Poor        PG       Yes
15     Poor        UG        No
16     Poor        UG       Yes
17     Poor        UG       Yes
18     Good    School        No
19     Poor        PG       Yes
20  Average    School       Yes
21  Average        PG        No
22     Poor        PG       Yes
23     Good    School        No
24  Average        PG       Yes
25     Good    School        No
26     Poor        PG        No
27     Poor        PG        No
28     Poor    School        No
29  Average        UG       Yes
30  Average        UG        No
31     Poor    School       Yes
32  Average        UG       Yes
33     Good        PG       Yes
34  Average    School        No
35     Poor    School       Yes
36     Good        UG       Yes
37  Average        PG       Yes
38     Good    School        No
39     Poor        PG        No
40     Good    School        No
41     Good        PG       Yes
42     Good        PG       Yes
43     Poor        PG        No
44  Average        UG        No
45     Poor        PG       Yes
46     Poor        PG        No
47     Good        PG       Yes
48     Good        UG       Yes
49     Good        UG        No

In [ ]:
df.shape

(50, 3)

In [ ]:
X=df.drop('purchased', axis=1)
X

     review education
0   Average    School
1      Poor        UG
2      Good        PG
3      Good        PG
4   Average        UG
5   Average    School
6      Good    School
7      Poor    School
8   Average        UG
9      Good        UG
10     Good        UG
11     Good        UG
12     Poor    School
13  Average    School
14     Poor        PG
15     Poor        UG
16     Poor        UG
17     Poor        UG
18     Good    School
19     Poor        PG
20  Average    School
21  Average        PG
22     Poor        PG
23     Good    School
24  Average        PG
25     Good    School
26     Poor        PG
27     Poor        PG
28     Poor    School
29  Average        UG
30  Average        UG
31     Poor    School
32  Average        UG
33     Good        PG
34  Average    School
35     Poor    School
36     Good        UG
37  Average        PG
38     Good    School
39     Poor        PG
40     Good    School
41     Good        PG
42     Good        PG
43     Poor        PG
44  Average        UG
45     Poor        PG
46     Poor        PG
47     Good        PG
48     Good        UG
49     Good        UG

In [ ]:
y=df['purchased']

In [ ]:
y

0      No
1      No
2      No
3      No
4      No
5     Yes
6      No
7     Yes
8      No
9     Yes
10    Yes
11    Yes
12     No
13     No
14    Yes
15     No
16    Yes
17    Yes
18     No
19    Yes
20    Yes
21     No
22    Yes
23     No
24    Yes
25     No
26     No
27     No
28     No
29    Yes
30     No
31    Yes
32    Yes
33    Yes
34     No
35    Yes
36    Yes
37    Yes
38     No
39     No
40     No
41    Yes
42    Yes
43     No
44     No
45    Yes
46     No
47    Yes
48    Yes
49     No
Name: purchased, dtype: object

In [ ]:
df.head(15)

     review education purchased
0   Average    School        No
1      Poor        UG        No
2      Good        PG        No
3      Good        PG        No
4   Average        UG        No
5   Average    School       Yes
6      Good    School        No
7      Poor    School       Yes
8   Average        UG        No
9      Good        UG       Yes
10     Good        UG       Yes
11     Good        UG       Yes
12     Poor    School        No
13  Average    School        No
14     Poor        PG       Yes

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.2, random_state=786)

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
oe=OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']]) # telling my encoder the order in asc order

In [ ]:
# X_train=oe.fit_transform(X_train)

In [ ]:
# X_train

In [ ]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [ ]:
X_train=oe.transform(X_train)

In [ ]:
X_train

array([[1., 2.],
       [1., 1.],
       [1., 0.],
       [0., 2.],
       [0., 0.],
       [0., 2.],
       [0., 1.],
       [1., 2.],
       [0., 2.],
       [2., 2.],
       [1., 1.],
       [0., 2.],
       [0., 0.],
       [1., 0.],
       [2., 2.],
       [2., 1.],
       [2., 2.],
       [2., 0.],
       [0., 1.],
       [2., 2.],
       [2., 0.],
       [0., 0.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [2., 2.],
       [1., 1.],
       [0., 2.],
       [0., 1.],
       [2., 0.],
       [1., 0.],
       [0., 2.],
       [2., 1.],
       [2., 1.],
       [1., 0.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [2., 0.],
       [1., 1.]])

In [ ]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le=LabelEncoder()

In [ ]:
le.fit(y_train)

LabelEncoder()

In [ ]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [ ]:
le.fit(y_train)

LabelEncoder()

In [ ]:
y_train=le.transform(y_train)

In [ ]:
y_test=le.transform(y_test)

In [ ]:
y_train

array([0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0])

In [ ]:
df.head(20)

     review education purchased
0   Average    School        No
1      Poor        UG        No
2      Good        PG        No
3      Good        PG        No
4   Average        UG        No
5   Average    School       Yes
6      Good    School        No
7      Poor    School       Yes
8   Average        UG        No
9      Good        UG       Yes
10     Good        UG       Yes
11     Good        UG       Yes
12     Poor    School        No
13  Average    School        No
14     Poor        PG       Yes
15     Poor        UG        No
16     Poor        UG       Yes
17     Poor        UG       Yes
18     Good    School        No
19     Poor        PG       Yes